- dcapal-frontend/src/components/allocationFlow/endStep/index.js
- dcapal-frontend/src/components/allocationFlow/index.js
- dcapal-frontend/src/components/allocationFlow/investStep.js
- dcapal-frontend/src/workers/solver.js
- dcapal-optimizer-wasm/src/lib.rs
- dcapal-optimizer-wasm/src/optimize.rs
> Add buy-and-sell algorithm

- dcapal-frontend/demo/dcapal-60-40.json
- dcapal-frontend/demo/dcapal-all-seasons.json
- dcapal-frontend/src/app/config.js
- dcapal-frontend/src/components/core/inputNumber.js
- dcapal-frontend/src/routes/demoPage.js
- dcapal-frontend/src/routes/router.js
> Add demo portfolios

- .gitignore
- README.md
```mermaid
flowchart LR
Frontend[Frontend] ---|"/api/external/search?q={query}<br>/api/external/chart/${symbol}"|nginx[nginx]
subgraph dcapal.com
nginx---TradFiProvider[TradFi Provider]
nginx---Backend[Backend]
Backend---CryptoProvider[Crypto Provider REST API]
Backend---|"/assets/fiat<br>/assets/crypto<br>/price/{base}?quote={quote}"|Redis[Redis]
end
```
> [DOC] Improve README and introduce naive system architecture

- dcapal-frontend/src/components/allocationFlow/endStep/allocateCard.js
- dcapal-frontend/src/components/core/footer.js
> [BUG-FIX] Wrap problem in the endstep and improved accessibility

- dcapal-frontend/package-lock.json
- dcapal-frontend/package.json
- dcapal-frontend/src/app/config.js
- dcapal-frontend/src/app/index.js
- dcapal-frontend/src/app/store.js
- dcapal-frontend/src/components/allocationFlow/portfolioStep/index.js
- dcapal-frontend/src/components/allocationFlow/portfolioStep/portfolioSlice.js
> Refresh prices every 5 minutes

- dcapal-frontend/src/components/allocationFlow/ccyStep/index.js
See [here](https://github.com/leonardoarcari/dcapal/issues/10) for the bug report.
Closes #10.
> Keep currency selected on back navigation

- .github/ISSUE_TEMPLATE/01-question-support.md
- .github/ISSUE_TEMPLATE/02-security-report.md
- .github/ISSUE_TEMPLATE/03-enhancement-request.md
- .github/ISSUE_TEMPLATE/04-feature-request.md
- .github/ISSUE_TEMPLATE/05-bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
Introduce PR template and Issue template to provide a clear structure to them.
Issues without template are still available but in the future you could choose to force users to use the template (see config.yml)
/
#42 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> [DEV-EXP] Add Pull request and Issue templates

- .github/ISSUE_TEMPLATE/01-question-support.md
- .github/ISSUE_TEMPLATE/02-security-report.md
- .github/ISSUE_TEMPLATE/03-enhancement-request.md
- .github/ISSUE_TEMPLATE/04-feature-request.md
- .github/ISSUE_TEMPLATE/05-bug-report.md
Introduction of missing headers to generate issue templates
Nothing
1. #49 
Nothing
> Resolve bug on issue templates

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Introduce contributing and code of conduct files
Nothing
1. #46 
Nothing
> [SUPPORT] Introduce CONTRIBUTING and CODE OF CONDUCT files

- dcapal-frontend/src/routes/demoPage.js
- dcapal-frontend/src/routes/errorPage.js
- dcapal-frontend/src/routes/notFoundPage.js
Import missing deps on all components.
/
Resolve #119 
/
> Fix - Error on not found page and error page

- dcapal-frontend/src/components/allocationFlow/endStep/allocateCard.js
- dcapal-frontend/src/components/allocationFlow/endStep/index.js
**Without cash position**
<p alight="center"><img src="https://github.com/leonardoarcari/dcapal/assets/811969/5620f6ae-3592-4b08-9bce-53d7694bdaec" width=520/></p>
**With cash position**
<p alight="center"><img src="https://github.com/leonardoarcari/dcapal/assets/811969/6ca377af-bfc4-4d0c-91c8-f3ad4d9534af" width=520/></p>
1. #122
> FE: Do not weigh unallocated cash if portfolio does not have liquidity position

- dcapal-frontend/src/components/allocationFlow/steps/invest.js
The issue should now be solved:
https://github.com/leonardoarcari/dcapal/assets/62722102/7f49f798-661d-4f49-808d-9de9d573184a
> Fix no budget suggestion when "Fractional Shares" option is selected

- .github/workflows/publish.yml
- dcapal-frontend/package-lock.json
- dcapal-frontend/src/components/allocationFlow/steps/end/allocateCard.js
- dcapal-optimizer-wasm/src/optimize/advanced.rs
Fix fee amount and impact calculation frontend side
**Bug**
> Hotfix: Wrong fee amount and impact calculation on FE

- .github/workflows/build-test.yml
- .github/workflows/deploy.yml
- .github/workflows/publish.yml
- Cargo.lock
- Cargo.toml
- dcapal-backend/Cargo.toml
- dcapal-backend/src/app/infra/stats.rs
- dcapal-backend/src/lib.rs
- dcapal-backend/src/ports/inbound/rest/mod.rs
- dcapal-optimizer-wasm/Cargo.toml
- Bump Rust dependencies and fix compilation issues
- Fix broken Dcapal Docker repo in Github actions
> build(deps): bump Rust dependencies and MSRV to v1.79

- dcapal-frontend/package-lock.json
- dcapal-frontend/package.json
- dcapal-frontend/webpack.dev.js
> build(deps): bump JS dependencies (2)

- dcapal-frontend/src/components/allocationFlow/steps/portfolio/assetCard.js
Fixes #420 
https://github.com/user-attachments/assets/4d4fb4d4-2314-4b18-aaa2-4269a945583a
> feat(fe): allow fractional shares in Equity asset class

- dcapal-frontend/package-lock.json
- dcapal-frontend/package.json
- dcapal-frontend/src/components/core/launchBtn.js
- dcapal-frontend/src/index.js
- dcapal-frontend/src/theme/components/button.js
- dcapal-frontend/src/theme/index.js
- dcapal-frontend/webpack.common.js
First appearance of Chakra UI in DcaPal. This PR adds Chakra UI dependencies, customizes Button theme to look like current DcaPal UI and ports `<LaunchBtn>` component to Chrakra.
https://github.com/user-attachments/assets/48146d19-0d6b-4a54-ad5a-020e13b0b54b
> feat(fe): add Chakra UI

- dcapal-frontend/src/components/core/navBar.js
- dcapal-frontend/src/components/core/rootCard.js
- dcapal-frontend/src/index.html
- dcapal-frontend/src/index.js
- dcapal-frontend/src/routes/root.js
Lighthouse `performance` and `a11y` metrics score bad, especially on mobile ([report](https://pagespeed.web.dev/analysis/https-www-dcapal-com/87jymawnrh?form_factor=mobile)). This PR fixes the most critical ones.
> feat(fe): improve Lighthouse performance and a11y metrics

- .github/workflows/build-test.yml
- .github/workflows/deploy.yml
Bump `@actions/upload-artifact` and `@actions/download-artifact` to v4
> ops: bump @actions/artifact to v4

- Cargo.toml
Resolves https://github.com/dcapal/dcapal/discussions/462
> build: enable LTO

- dcapal-backend/config/supabase/config.toml
- dcapal-frontend/package-lock.json
- dcapal-frontend/public/locales/en/translation.json
- dcapal-frontend/public/locales/it/translation.json
- dcapal-frontend/src/components/allocationFlow/steps/portfolio/index.js
- dcapal-frontend/src/routes/aboutPage.js
> feat(554): Improve UX for the allocation flow

- Cargo.lock
- Cargo.toml
- Makefile
- dcapal-backend/Cargo.toml
- dcapal-backend/docker/Dockerfile
- dcapal-backend/src/error.rs
- dcapal-backend/src/lib.rs
- dcapal-backend/src/ports/inbound/rest/mod.rs
- dcapal-backend/src/ports/outbound/adapter/yahoo.rs
- dcapal-frontend/package-lock.json
- dcapal-frontend/public/locales/en/translation.json
- dcapal-frontend/public/locales/it/translation.json
- dcapal-frontend/src/app/config.js
- dcapal-frontend/src/app/providers.js
- dcapal-frontend/src/components/allocationFlow/steps/portfolio/index.js
- dcapal-frontend/src/components/allocationFlow/steps/portfolio/searchBar.js
- dcapal-frontend/src/routes/aboutPage.js
* fix: supabase config
* feat: improve the allocation flow UX
* format: apply npm run format
closes #555
> fix: YF not allowing request from server
